apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagger-prod
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: services
  source:
    repoURL: https://flagger.app
    targetRevision: latest
    chart: charts/flagger
    targetRevision: 1.21.0
    helm:
     parameters:
      - name: meshProvider
        value: istio
 #     - name: include-crds
 #       value: https://raw.githubusercontent.com/fluxcd/flagger/main/artifacts/flagger/crd.yaml
      - name: crd.create
        value: "false"
      - name: metricsServer
        value: http://prometheus.monitoring:9090
#    plugin:
#      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
   automated:
    prune: true
    selfHeal: true
   syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true