apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: 'istio-operator'
    namespace: istio-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/charts/istio-operator
    repoURL: 'https://github.com/istio/istio'
    targetRevision: release-1.7
  project: services
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
