apiVersion: v1
kind: Secret
metadata:
  name: tharpool-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/tharpooljha/argocd_demo
  name: tharpool-private-repo
  project: dev