apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-addons
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    path: samples/addons
    repoURL: https://github.com/istio/istio
    targetRevision: release-1.7
  project: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
