apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dev
spec:
  selector:
    matchLabels:
      app: node-app-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app-dev
    spec:
      containers:
        - name: node-app
          image: ghcr.io/tharpooljha/node_app:1.0.0-broken
          ports:
            - containerPort: 3000

          