apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-infastructure
spec:
  generators:
  - list:
    elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
      metadata: {}
      spec:
        project: "development"
        source:
          targetRevision: HEAD
          repoURL: https://github.com/tharpooljha/argocd_demo
          path: '{{path}}/dev'
        destination: {}
  - git:
      repoURL: https://github.com/tharpooljha/argocd_demo
      revision: HEAD
      directories:
      - path: deployments/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: services # If something is an app and not a service, we need another entry here.
      source:
        repoURL: https://github.com/tharpooljha/argocd_demo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        # this doesn't work well when istio-addons should be on istio-system. This template seems to override.