apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-infastructure
spec:
  generators:
  - git:
      repoURL: https://github.com/tharpooljha/argocd_demo
      revision: HEAD
      directories:
      - path: deployments/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: services
      source:
        repoURL: https://github.com/tharpooljha/argocd_demo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'