apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/tharpooljha/argocd_demo
      revision: HEAD
      directories:
      - path: '{{cluster}}/infastructure/{{environment}}'
  template:
    metadata:
      name: '{{cluster}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tharpooljha/argocd_demo
        targetRevision: HEAD
        path: '{{path}}'
      destination: {}