apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# additional resources like ingress rules, cluster and repository secrets.
resources:
 - namespace.yaml
# - configmap.yaml
#- clusters-secrets.yaml
#- repos-secrets.yaml

