apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-guestbook-dev-xperience-aks-cluster-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      # v0.2.0+ form - does not require cluster/URL keys (but are still supported)
      - cluster: dev-xperience-aks-cluster
        url: https://20.94.165.217
        gitRepo: https://github.com/argoproj/argocd-example-apps.git
        appPath: guestbook
        appBranch: HEAD
        project: qa 

 
  template:
    metadata:
      name: '{{cluster}}'
    spec:
      project: '{{project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: '{{gitRepo}}'
        targetRevision: '{{appBranch}}'
        path: '{{appPath}}'
        directory:
          recurse: true
      destination:
        server: '{{url}}'
        namespace: '{{project}}'