apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-controlplane
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: 'istio-controlplane'
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: istio-controlplane
    repoURL: 'https://github.com/argoproj/argoproj-deployments'
    targetRevision: HEAD
  project: services
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: true
