apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-infastructure-appsets
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  labels:
    environment: qa

spec:
  # The project the application belongs to.
  project: qa
  source:
    repoURL: https://github.com/tharpooljha/argocd_demo
    targetRevision: HEAD
    path: 'apps/applicationsets/qa'
    # plugin:
    #   name: argocd-vault-plugin-kustomize
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
     - ApplyOutOfSyncOnly=true
     - CreateNamespace=true