apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: dev
spec:
  encryptedData:
    foo: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: dev
data:
  foo: bar  # <- base64 encoded "bar"