apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - image: ghcr.io/argoproj/argocd:2.4.0-dd4dbe2a
        name: argocd
        ports:
        - containerPort: 8080