apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-prod
spec:
  selector:
    matchLabels:
      app: node-app-prod
#  replicas: 2
  template:
    metadata:
      labels:
        app: node-app-prod
    spec:
      containers:
        - name: node-app-prod
          image: ghcr.io/tharpooljha/node-app-demo:latest
          ports:
            - containerPort: 3000